server:
  port: 10004

spring:
  application:
    name: cloud-auth

  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://47.106.11.84:3306/zuul-auth?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wangshihao
    druid:
      driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: wangshihao

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
      service-url:
        defaultZone: http://localhost:10001/eureka/

#logging:
#  config: classpath:logback.xml
#  level:
#    org:
#      springframework:
#        web: info
###feign 默认关闭熔断，请看HystrixFeignConfiguration

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1