server:
  port: 20001

spring:
  application:
    name: cloud-eureka-client

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/


