apollo:
  meta: http://47.106.11.84:8080
  bootstrap:
    enabled: true
    namespaces: application,ADITUM.eureka

server:
  port: ${port:10000}

spring:
  application:
    name: ${name:default-application-name}

eureka:
  instance:
    hostname: ${hostname:localhost}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/